on: 
 push
name: Jira Issue Creation Demo
jobs:
  jiraIssueCreation:
    name: Jira Issue Creation Demo
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Login
      uses: atlassian/gajira-login@master
      env:
       JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
       JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
       JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
         
    - name: Find Issue Key
      uses: ./
      with:
       project: GJD
       issuetype: Task
       description: Created automatically via GitHub Actions
       from: commits

    - name: Transition issue
      uses: atlassian/gajira-transition@master
      with:
        issue: ${{ steps.create.outputs.issue }}
        transition: "In Progress"
        
    - name: Comment issue
      uses: atlassian/gajira-comment@master
        
